update some error validation in github action workflows

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -51,5 +51,12 @@ jobs:
            echo SESSION_SECRET=${SESSION_SECRET} >> .env
            cat .env
 
-    - run: npm run build --if-present
-    - run: pm2 restart todobackend
+
+    - name: Build project
+      run: npm run build --if-present
+
+    - name: Start PM2 server
+      run: pm2 restart todobackend || echo "PM2 restart failed"
+
+    - name: Check PM2 logs
+      run: pm2 logs
